# Generated by Django 4.2.11 on 2024-04-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('patent_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('patent_cntry_cd', models.CharField(max_length=255)),
                ('patent_keyword_val', models.CharField(max_length=255)),
                ('patent_nm', models.CharField(max_length=255)),
                ('patent_kor_nm', models.CharField(max_length=255)),
                ('patent_applcnt_nm', models.CharField(max_length=255)),
                ('patent_applcnt_kor_nm', models.CharField(max_length=255)),
                ('patent_applcnt_cntry_cd', models.CharField(max_length=255)),
                ('patent_og_text_file_nm', models.CharField(max_length=255)),
                ('patent_og_text_file_extnsn_nm', models.CharField(max_length=255)),
                ('patent_create_dt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AttachFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_nm', models.CharField(max_length=255)),
                ('file_extnsn_nm', models.CharField(max_length=255)),
                ('file_size_val', models.IntegerField()),
                ('file_size_unit_nm', models.CharField(max_length=255)),
                ('file_ver_val', models.IntegerField()),
                ('file_upload_user_id', models.CharField(max_length=255)),
                ('file_loc_val', models.CharField(max_length=255)),
                ('create_user_id', models.CharField(max_length=255)),
                ('create_dtm', models.DateTimeField()),
                ('modify_user_id', models.CharField(max_length=255)),
                ('modify_dtm', models.DateTimeField()),
                ('patent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attach_file', to='patent.patent')),
            ],
            options={
                'unique_together': {('file_nm', 'file_extnsn_nm')},
            },
        ),
    ]
